# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"alacritty" = "ï„ "
"home assistant"="ó°Ÿ"
"chrome" = "îƒ"
"github" = "îœ‰"
"gitlab" = "î™œ"
"google meet"="ó°»’"
"google docs" = "ó°ˆ™"
"evidenced" = "ó±ˆ¹"
"excalidraw" = "ó°”™"
"stack overflow" = "ó°“Œ"
"google" = "ó°Š­"
"jira"="ó°Œƒ"
"reddit"="ó°‘"
"youtube"="ó°—ƒ"
"plex"="ó°šº"
"datadog"="ó°©„"
"meet "="ó°»’"
"calendar"="ó°ƒ­"
"hacker news"="îœš"
"private browsing" = "ó°—¹"
"firefox" = "ó°ˆ¹"
"libreoffice calc" = "ïƒ"
"libreoffice writer" = "ïœ˜"
"libreoffice" = "ï£…"
"vim" = "îŸ…"
"menu" = "ï¡œ"
"calculator" = "ó°ƒ¬"
"speedcrunch" = "ó°ƒ¬"
"videostream" = "ï˜˜"
"mpv" = "ïœª"
"music" = "ï€"
"disk usage" = "ïŸ‰"
".pdf" = "ï‘"
"spotify" = "ó°“‡"
"psst-gui" = "ó°“‡"
"foot" = "ï’‰"
"gnome-terminal-server"="ó°†"
"sublime_text" = "îª"
"pavucontrol" = "ó°•¾"
"ulauncher" = "â–¼"
"code" = "ó°¨"
"nemo" = "ó°‰‹"
"file-roller" = "ó°€¼"
"sublime_merge" = "îœ¥"
"jetbrains-pycharm" = "ó°Œ "
"jetbrains-goland" = "î˜§"
"eog" = "ó°‹©"
"nomacs" = "ó°‹©"
"software" = "ïŠ"
"gnome-power-statistics"="ó°¾"
"audacity"="ïŸŠ"
"gimp"="î¬ª"
"inkscape"="ó°€"
"youtube"="ï…ª"
"obsidian"="ó°®‹"
"printer"="ó°ª"
"steam"="ó°““"
"slack"="ó°’±"
"subsurface"="ó°·„"
"meld"="ó°½œ"
"seahorse"="ó±•´"
"gedit"="ó°­¸"
"virtual machine"="ó°’‹"
"qemu"="ó±„„"
"csv"="î®·"
"1password"="ó°¢"
"blueman-manager"="ó°‚¯"
"jetbrains-toolbox"="ó°†¦"
"aws vpn client"="ó°–‚"
"heroic"="ó±¢¾"
"disks"="ó°‹Š"
"godot"="î™Ÿ"
"zoom"="ó°»’"
"factorio"="ó°ˆ"
"openttd"="îƒ"
"copyq"="ïƒ„"
"kdenlive"="ïŒ¼"

[other]
fallback_icon = "ğŸ¤¨"
deduplicate_icons = false
