# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"alacritty" = "ï„ "
"github" = "ï„“"
"gitlab" = "ïŠ–"
"google" = "ï† "
"private browsing" = "ïˆ›"
"firefox" = "ï‰©"
"chrome" = "ï‰¨"
"file manager" = "ï¼"
"libreoffice calc" = "ïƒ"
"libreoffice writer" = "ïœ˜"
"libreoffice" = "ï£…"
"vim" = "îŸ…"
"gthumb" = "ï€¾"
"menu" = "ï¡œ"
"calculator" = "ï—«"
"transmission" = "ï€™"
"videostream" = "ï˜˜"
"mpv" = "ïœª"
"music" = "ï€"
"disk usage" = "ïŸ‰"
".pdf" = "ïœ¤"
"spotify" = "ï†¼"
"foot" = "ï’‰"
"gnome-terminal-server"="ï’‰"
"sublime_text" = "îª"
"pavucontrol" = "ï€¨"
"ulauncher" = "â–¼"
"code" = "îœŒ"
"nemo" = "ï¼"
"file-roller" = "ï«ƒ"
"sublime_merge" = "îœ¥"
"jetbrains-pycharm" = "ï Ÿ"
"eog" = "ï€¾"
"software" = "ïŠ"
"gnome-power-statistics"="ï‰"
"audacity"="ïŸŠ"
"gimp"="ï‡¼"
"inkscape"="îŠ¦"
"plex"="ï…„"
"youtube"="ï…ª"
"obsidian"="ğŸ’"
"printer"="ï€¯"
"steam"="ï†¶"
"slack"="ï†˜"
[other]
fallback_icon = "ğŸ¤¨"
deduplicate_icons = false
