- name: Ensure .ssh directory exists
  file:
    path: /home/{{ user }}/.ssh
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700

- name: Ensure .ssh/sockets directory exists for ControlPath
  file:
    path: /home/{{ user }}/.ssh/sockets
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700

- name: Configure SSH client options in .ssh/config
  blockinfile:
    path: /home/{{ user }}/.ssh/config
    create: yes
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600
    marker: "# {mark} ANSIBLE MANAGED - Global SSH options"
    insertbefore: BOF
    block: |
      AddKeysToAgent yes

      Host *
        ControlMaster auto
        ControlPath ~/.ssh/sockets/%r@%h:%p

      Host gitea.wjdp.uk
        Port 222
