sway_apt_repos: []

sway_apt_packages:
  - sway
  - swaylock
  - swayidle
  - fd-find
  - wl-clipboard
  - suckless-tools
  - waybar
  - fonts-font-awesome
  - xdg-desktop-portal-wlr
  - wf-recorder
  - grim
  - slurp
  - mako-notifier
  - wofi

sway_cachyos_packages:
  - sway
  - swaylock
  - swayidle
  - swaybg
  - wl-clipboard
  - waybar
  - wf-recorder
  - grim
  - slurp
  - mako
  - wofi