distro: ubuntu

git_email: will@wegift.io
git_signing_key: 1B48523D91781A7F5CEC929B7CA9BF9F444BF7C8

wallpaper: $HOME/dotfiles/wallpapers/1440p/richard-horvath-RAZU_R66vUc-unsplash.jpg
lockpaper_path: $HOME/dotfiles/wallpapers/tile/square-tubes-green.png
lockpaper_scaling: tile

screen_left: DP-1
screen_left_scale: 1
screen_left_w: 2560
screen_left_h: 1440

screen_right: HDMI-A-1
screen_right_scale: 1
screen_right_w: 2560
screen_right_h: 1440

screen_internal: eDP-1
screen_internal_w: 2880
screen_internal_h: 1800
screen_internal_scale: 1.5

screen_left_extra: DP-3
